version: '3.9'

services:
  wiremock:
    image: rodolpheche/wiremock:2.27.2
    ports:
      - "${API_MOCK_PORT-8080}:8080"
    volumes:
      - "./PriceAggregator.IntegrationTests/stubs:/home/wiremock/mappings"
